baseURL = 'https://chipnomad.org/'
languageCode = 'en-us'
title = 'ChipNomad'

enableEmoji = true

[markup.goldmark.renderer]
  unsafe = true

[markup.tableOfContents]
  startLevel = 2
  endLevel = 3

[params]
  description = 'ChipNomad - a chiptune tracker for handheld consoles'
  title = 'ChipNomad'
  images = ['site-cover.jpg']

[social]
  twitter = 'megus_music'

[menu]
[[menu.main]]
  name = 'Download'
  url = 'https://github.com/Megus/chipnomad-tracker/releases'
  weight = 10
[[menu.main]]
  name = 'Manual'
  pageRef = '/manual'
  weight = 20
[[menu.main]]
  name = 'Discord'
  url = 'https://discord.gg/PJarAn2QCW'
  weight = 30
[[menu.main]]
  name = 'GitHub'
  url = 'https://github.com/Megus/chipnomad-tracker'
  weight = 40